# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='service.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\rservice.proto\"c\n\x0bModelParams\x12\x14\n\x0csepal_length\x18\x01 \x01(\x02\x12\x13\n\x0bsepal_width\x18\x02 \x01(\x02\x12\x14\n\x0cpetal_length\x18\x03 \x01(\x02\x12\x13\n\x0bpetal_width\x18\x04 \x01(\x02\"9\n\rModelResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x17\n\x0fpredicted_class\x18\x02 \x01(\x05\x32<\n\x0fModelPrediction\x12)\n\x07predict\x12\x0c.ModelParams\x1a\x0e.ModelResponse\"\x00\x62\x06proto3'
)




_MODELPARAMS = _descriptor.Descriptor(
  name='ModelParams',
  full_name='ModelParams',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sepal_length', full_name='ModelParams.sepal_length', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sepal_width', full_name='ModelParams.sepal_width', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='petal_length', full_name='ModelParams.petal_length', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='petal_width', full_name='ModelParams.petal_width', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=17,
  serialized_end=116,
)


_MODELRESPONSE = _descriptor.Descriptor(
  name='ModelResponse',
  full_name='ModelResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='ModelResponse.success', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='predicted_class', full_name='ModelResponse.predicted_class', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=118,
  serialized_end=175,
)

DESCRIPTOR.message_types_by_name['ModelParams'] = _MODELPARAMS
DESCRIPTOR.message_types_by_name['ModelResponse'] = _MODELRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ModelParams = _reflection.GeneratedProtocolMessageType('ModelParams', (_message.Message,), {
  'DESCRIPTOR' : _MODELPARAMS,
  '__module__' : 'service_pb2'
  # @@protoc_insertion_point(class_scope:ModelParams)
  })
_sym_db.RegisterMessage(ModelParams)

ModelResponse = _reflection.GeneratedProtocolMessageType('ModelResponse', (_message.Message,), {
  'DESCRIPTOR' : _MODELRESPONSE,
  '__module__' : 'service_pb2'
  # @@protoc_insertion_point(class_scope:ModelResponse)
  })
_sym_db.RegisterMessage(ModelResponse)



_MODELPREDICTION = _descriptor.ServiceDescriptor(
  name='ModelPrediction',
  full_name='ModelPrediction',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=177,
  serialized_end=237,
  methods=[
  _descriptor.MethodDescriptor(
    name='predict',
    full_name='ModelPrediction.predict',
    index=0,
    containing_service=None,
    input_type=_MODELPARAMS,
    output_type=_MODELRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_MODELPREDICTION)

DESCRIPTOR.services_by_name['ModelPrediction'] = _MODELPREDICTION

# @@protoc_insertion_point(module_scope)
